# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apipackages_api import ApipackagesApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApipackagesApi(unittest.TestCase):
    """ApipackagesApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apipackages_api.ApipackagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apipackages_create(self):
        """Test case for apipackages_create

        """
        pass

    def test_apipackages_delete(self):
        """Test case for apipackages_delete

        """
        pass

    def test_apipackages_list(self):
        """Test case for apipackages_list

        """
        pass

    def test_apipackages_partial_update(self):
        """Test case for apipackages_partial_update

        """
        pass

    def test_apipackages_read(self):
        """Test case for apipackages_read

        """
        pass

    def test_apipackages_update(self):
        """Test case for apipackages_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
