# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apipackagetags_api import ApipackagetagsApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApipackagetagsApi(unittest.TestCase):
    """ApipackagetagsApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apipackagetags_api.ApipackagetagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apipackagetags_create(self):
        """Test case for apipackagetags_create

        """
        pass

    def test_apipackagetags_delete(self):
        """Test case for apipackagetags_delete

        """
        pass

    def test_apipackagetags_list(self):
        """Test case for apipackagetags_list

        """
        pass

    def test_apipackagetags_partial_update(self):
        """Test case for apipackagetags_partial_update

        """
        pass

    def test_apipackagetags_read(self):
        """Test case for apipackagetags_read

        """
        pass

    def test_apipackagetags_update(self):
        """Test case for apipackagetags_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
