# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apieditions_api import ApieditionsApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApieditionsApi(unittest.TestCase):
    """ApieditionsApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apieditions_api.ApieditionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apieditions_create(self):
        """Test case for apieditions_create

        """
        pass

    def test_apieditions_delete(self):
        """Test case for apieditions_delete

        """
        pass

    def test_apieditions_list(self):
        """Test case for apieditions_list

        """
        pass

    def test_apieditions_partial_update(self):
        """Test case for apieditions_partial_update

        """
        pass

    def test_apieditions_read(self):
        """Test case for apieditions_read

        """
        pass

    def test_apieditions_update(self):
        """Test case for apieditions_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
