# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apiresources_api import ApiresourcesApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApiresourcesApi(unittest.TestCase):
    """ApiresourcesApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apiresources_api.ApiresourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apiresources_create(self):
        """Test case for apiresources_create

        """
        pass

    def test_apiresources_delete(self):
        """Test case for apiresources_delete

        """
        pass

    def test_apiresources_list(self):
        """Test case for apiresources_list

        """
        pass

    def test_apiresources_partial_update(self):
        """Test case for apiresources_partial_update

        """
        pass

    def test_apiresources_read(self):
        """Test case for apiresources_read

        """
        pass

    def test_apiresources_update(self):
        """Test case for apiresources_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
