# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apifsobject_api import ApifsobjectApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApifsobjectApi(unittest.TestCase):
    """ApifsobjectApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apifsobject_api.ApifsobjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apifsobject_create(self):
        """Test case for apifsobject_create

        """
        pass

    def test_apifsobject_delete(self):
        """Test case for apifsobject_delete

        """
        pass

    def test_apifsobject_list(self):
        """Test case for apifsobject_list

        """
        pass

    def test_apifsobject_partial_update(self):
        """Test case for apifsobject_partial_update

        """
        pass

    def test_apifsobject_read(self):
        """Test case for apifsobject_read

        """
        pass

    def test_apifsobject_update(self):
        """Test case for apifsobject_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
