# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.models.package_tag import PackageTag  # noqa: E501
from progdbclient.rest import ApiException


class TestPackageTag(unittest.TestCase):
    """PackageTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageTag(self):
        """Test PackageTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = progdbclient.models.package_tag.PackageTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
