# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apimodule_api import ApimoduleApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApimoduleApi(unittest.TestCase):
    """ApimoduleApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apimodule_api.ApimoduleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apimodule_create(self):
        """Test case for apimodule_create

        """
        pass

    def test_apimodule_delete(self):
        """Test case for apimodule_delete

        """
        pass

    def test_apimodule_list(self):
        """Test case for apimodule_list

        """
        pass

    def test_apimodule_partial_update(self):
        """Test case for apimodule_partial_update

        """
        pass

    def test_apimodule_read(self):
        """Test case for apimodule_read

        """
        pass

    def test_apimodule_update(self):
        """Test case for apimodule_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
