# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.models.source_replica import SourceReplica  # noqa: E501
from progdbclient.rest import ApiException


class TestSourceReplica(unittest.TestCase):
    """SourceReplica unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceReplica(self):
        """Test SourceReplica"""
        # FIXME: construct object with mandatory attributes with example values
        # model = progdbclient.models.source_replica.SourceReplica()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
