# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apipackage_api import ApipackageApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApipackageApi(unittest.TestCase):
    """ApipackageApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apipackage_api.ApipackageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apipackage_create(self):
        """Test case for apipackage_create

        """
        pass

    def test_apipackage_delete(self):
        """Test case for apipackage_delete

        """
        pass

    def test_apipackage_list(self):
        """Test case for apipackage_list

        """
        pass

    def test_apipackage_partial_update(self):
        """Test case for apipackage_partial_update

        """
        pass

    def test_apipackage_read(self):
        """Test case for apipackage_read

        """
        pass

    def test_apipackage_update(self):
        """Test case for apipackage_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
