# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apireplica_api import ApireplicaApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApireplicaApi(unittest.TestCase):
    """ApireplicaApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apireplica_api.ApireplicaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apireplica_create(self):
        """Test case for apireplica_create

        """
        pass

    def test_apireplica_delete(self):
        """Test case for apireplica_delete

        """
        pass

    def test_apireplica_list(self):
        """Test case for apireplica_list

        """
        pass

    def test_apireplica_partial_update(self):
        """Test case for apireplica_partial_update

        """
        pass

    def test_apireplica_read(self):
        """Test case for apireplica_read

        """
        pass

    def test_apireplica_update(self):
        """Test case for apireplica_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
