# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apirepilca_api import ApirepilcaApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApirepilcaApi(unittest.TestCase):
    """ApirepilcaApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apirepilca_api.ApirepilcaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apirepilca_create(self):
        """Test case for apirepilca_create

        """
        pass

    def test_apirepilca_delete(self):
        """Test case for apirepilca_delete

        """
        pass

    def test_apirepilca_list(self):
        """Test case for apirepilca_list

        """
        pass

    def test_apirepilca_partial_update(self):
        """Test case for apirepilca_partial_update

        """
        pass

    def test_apirepilca_read(self):
        """Test case for apirepilca_read

        """
        pass

    def test_apirepilca_update(self):
        """Test case for apirepilca_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
