# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import progdbclient
from progdbclient.api.apisourcereplica_api import ApisourcereplicaApi  # noqa: E501
from progdbclient.rest import ApiException


class TestApisourcereplicaApi(unittest.TestCase):
    """ApisourcereplicaApi unit test stubs"""

    def setUp(self):
        self.api = progdbclient.api.apisourcereplica_api.ApisourcereplicaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apisourcereplica_create(self):
        """Test case for apisourcereplica_create

        """
        pass

    def test_apisourcereplica_delete(self):
        """Test case for apisourcereplica_delete

        """
        pass

    def test_apisourcereplica_list(self):
        """Test case for apisourcereplica_list

        """
        pass

    def test_apisourcereplica_partial_update(self):
        """Test case for apisourcereplica_partial_update

        """
        pass

    def test_apisourcereplica_read(self):
        """Test case for apisourcereplica_read

        """
        pass

    def test_apisourcereplica_update(self):
        """Test case for apisourcereplica_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
