# coding: utf-8

# flake8: noqa
"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from progdbclient.models.auth_token import AuthToken
from progdbclient.models.edition import Edition
from progdbclient.models.package import Package
from progdbclient.models.package_tag import PackageTag
from progdbclient.models.resource import Resource
