# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from progdbclient.configuration import Configuration


class Package(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'human_description': 'str',
        'machine_description': 'str',
        'main_prog_language': 'str',
        'package_collection': 'str',
        'kind': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'human_description': 'human_description',
        'machine_description': 'machine_description',
        'main_prog_language': 'main_prog_language',
        'package_collection': 'package_collection',
        'kind': 'kind'
    }

    def __init__(self, id=None, name=None, human_description=None, machine_description=None, main_prog_language=None, package_collection=None, kind=None, _configuration=None):  # noqa: E501
        """Package - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._human_description = None
        self._machine_description = None
        self._main_prog_language = None
        self._package_collection = None
        self._kind = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.human_description = human_description
        self.machine_description = machine_description
        self.main_prog_language = main_prog_language
        self.package_collection = package_collection
        if kind is not None:
            self.kind = kind

    @property
    def id(self):
        """Gets the id of this Package.  # noqa: E501


        :return: The id of this Package.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Package.


        :param id: The id of this Package.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Package.  # noqa: E501


        :return: The name of this Package.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Package.


        :param name: The name of this Package.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def human_description(self):
        """Gets the human_description of this Package.  # noqa: E501


        :return: The human_description of this Package.  # noqa: E501
        :rtype: str
        """
        return self._human_description

    @human_description.setter
    def human_description(self, human_description):
        """Sets the human_description of this Package.


        :param human_description: The human_description of this Package.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and human_description is None:
            raise ValueError("Invalid value for `human_description`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                human_description is not None and len(human_description) < 1):
            raise ValueError("Invalid value for `human_description`, length must be greater than or equal to `1`")  # noqa: E501

        self._human_description = human_description

    @property
    def machine_description(self):
        """Gets the machine_description of this Package.  # noqa: E501


        :return: The machine_description of this Package.  # noqa: E501
        :rtype: str
        """
        return self._machine_description

    @machine_description.setter
    def machine_description(self, machine_description):
        """Sets the machine_description of this Package.


        :param machine_description: The machine_description of this Package.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and machine_description is None:
            raise ValueError("Invalid value for `machine_description`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                machine_description is not None and len(machine_description) < 1):
            raise ValueError("Invalid value for `machine_description`, length must be greater than or equal to `1`")  # noqa: E501

        self._machine_description = machine_description

    @property
    def main_prog_language(self):
        """Gets the main_prog_language of this Package.  # noqa: E501


        :return: The main_prog_language of this Package.  # noqa: E501
        :rtype: str
        """
        return self._main_prog_language

    @main_prog_language.setter
    def main_prog_language(self, main_prog_language):
        """Sets the main_prog_language of this Package.


        :param main_prog_language: The main_prog_language of this Package.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and main_prog_language is None:
            raise ValueError("Invalid value for `main_prog_language`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                main_prog_language is not None and len(main_prog_language) < 1):
            raise ValueError("Invalid value for `main_prog_language`, length must be greater than or equal to `1`")  # noqa: E501

        self._main_prog_language = main_prog_language

    @property
    def package_collection(self):
        """Gets the package_collection of this Package.  # noqa: E501


        :return: The package_collection of this Package.  # noqa: E501
        :rtype: str
        """
        return self._package_collection

    @package_collection.setter
    def package_collection(self, package_collection):
        """Sets the package_collection of this Package.


        :param package_collection: The package_collection of this Package.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and package_collection is None:
            raise ValueError("Invalid value for `package_collection`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                package_collection is not None and len(package_collection) < 1):
            raise ValueError("Invalid value for `package_collection`, length must be greater than or equal to `1`")  # noqa: E501

        self._package_collection = package_collection

    @property
    def kind(self):
        """Gets the kind of this Package.  # noqa: E501


        :return: The kind of this Package.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this Package.


        :param kind: The kind of this Package.  # noqa: E501
        :type: str
        """

        self._kind = kind

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Package, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Package):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Package):
            return True

        return self.to_dict() != other.to_dict()
